<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ModelProfile;
use App\Models\User;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class ModelsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $models = [
            // Женские модели
            [
                'first_name' => 'Анастасия',
                'last_name' => 'Иванова',
                'email' => 'anastasia.ivanova@example.com',
                'phone' => '+7 (999) 111-11-01',
                'birth_date' => '2001-03-15',
                'gender' => 'female',
                'city' => 'Москва',
                'height' => 178,
                'weight' => 55,
                'bust' => 86,
                'waist' => 60,
                'hips' => 90,
                'eye_color' => 'Голубые',
                'hair_color' => 'Блондинка',
                'shoe_size' => 38,
                'clothing_size' => 'S',
                'bio' => 'Профессиональная модель с опытом работы на международных показах. Участвовала в показах Mercedes-Benz Fashion Week, работала с ведущими fashion-брендами.',
                'languages' => ['Русский', 'Английский'],
                'skills' => ['Подиумная ходьба', 'Фотопозирование', 'Актерское мастерство'],
                'instagram' => 'anastasia_ivanova_model',
                'categories' => ['fashion', 'runway', 'commercial'],
                'status' => 'active',
                'is_featured' => true,
                'experience_years' => 4,
            ],
            [
                'first_name' => 'Мария',
                'last_name' => 'Петрова',
                'email' => 'maria.petrova@example.com',
                'phone' => '+7 (999) 111-11-02',
                'birth_date' => '2002-07-22',
                'gender' => 'female',
                'city' => 'Санкт-Петербург',
                'height' => 175,
                'weight' => 52,
                'bust' => 84,
                'waist' => 58,
                'hips' => 88,
                'eye_color' => 'Зеленые',
                'hair_color' => 'Шатенка',
                'shoe_size' => 37,
                'clothing_size' => 'XS',
                'bio' => 'Молодая перспективная модель, специализируюсь на рекламных съемках и каталогах. Люблю экспериментировать с образами.',
                'languages' => ['Русский', 'Английский', 'Французский'],
                'skills' => ['Фотопозирование', 'Работа с камерой', 'Экспрессия'],
                'instagram' => 'maria_petrova_official',
                'categories' => ['commercial', 'catalog', 'editorial'],
                'status' => 'active',
                'is_featured' => true,
                'experience_years' => 2,
            ],
            [
                'first_name' => 'Екатерина',
                'last_name' => 'Смирнова',
                'email' => 'ekaterina.smirnova@example.com',
                'phone' => '+7 (999) 111-11-03',
                'birth_date' => '1998-11-05',
                'gender' => 'female',
                'city' => 'Москва',
                'height' => 180,
                'weight' => 58,
                'bust' => 88,
                'waist' => 62,
                'hips' => 92,
                'eye_color' => 'Карие',
                'hair_color' => 'Брюнетка',
                'shoe_size' => 39,
                'clothing_size' => 'S',
                'bio' => 'Опытная модель высокой моды. Работала с Vogue, Elle, Harper\'s Bazaar. Участница недель моды в Милане и Париже.',
                'languages' => ['Русский', 'Английский', 'Итальянский'],
                'skills' => ['Подиумная ходьба', 'High Fashion', 'Эдиториал'],
                'instagram' => 'katerina_smirnova',
                'telegram' => 'katerina_sm',
                'categories' => ['fashion', 'runway', 'editorial'],
                'status' => 'active',
                'is_featured' => true,
                'experience_years' => 7,
            ],
            [
                'first_name' => 'Виктория',
                'last_name' => 'Соколова',
                'email' => 'viktoria.sokolova@example.com',
                'phone' => '+7 (999) 111-11-04',
                'birth_date' => '2003-01-18',
                'gender' => 'female',
                'city' => 'Екатеринбург',
                'height' => 176,
                'weight' => 54,
                'bust' => 85,
                'waist' => 59,
                'hips' => 89,
                'eye_color' => 'Серые',
                'hair_color' => 'Русая',
                'shoe_size' => 38,
                'clothing_size' => 'S',
                'bio' => 'Начинающая модель с потрясающим потенциалом. Активно развиваюсь в модельной индустрии, открыта к новым проектам.',
                'languages' => ['Русский', 'Английский'],
                'skills' => ['Фотопозирование', 'Работа в студии'],
                'instagram' => 'vika_sokolova_model',
                'categories' => ['commercial', 'fitness', 'catalog'],
                'status' => 'active',
                'is_featured' => false,
                'experience_years' => 1,
            ],
            [
                'first_name' => 'Дарья',
                'last_name' => 'Новикова',
                'email' => 'daria.novikova@example.com',
                'phone' => '+7 (999) 111-11-05',
                'birth_date' => '2000-09-30',
                'gender' => 'female',
                'city' => 'Москва',
                'height' => 177,
                'weight' => 56,
                'bust' => 87,
                'waist' => 61,
                'hips' => 91,
                'eye_color' => 'Голубые',
                'hair_color' => 'Блондинка',
                'shoe_size' => 38,
                'clothing_size' => 'S',
                'bio' => 'Специализируюсь на beauty-съемках и рекламе косметических брендов. Имею опыт работы с L\'Oréal, Maybelline.',
                'languages' => ['Русский', 'Английский'],
                'skills' => ['Beauty', 'Крупный план', 'Экспрессия'],
                'instagram' => 'dasha_novikova',
                'categories' => ['beauty', 'commercial', 'editorial'],
                'status' => 'active',
                'is_featured' => true,
                'experience_years' => 3,
            ],
            [
                'first_name' => 'Алина',
                'last_name' => 'Козлова',
                'email' => 'alina.kozlova@example.com',
                'phone' => '+7 (999) 111-11-06',
                'birth_date' => '2001-05-12',
                'gender' => 'female',
                'city' => 'Казань',
                'height' => 174,
                'weight' => 53,
                'bust' => 83,
                'waist' => 57,
                'hips' => 87,
                'eye_color' => 'Карие',
                'hair_color' => 'Шатенка',
                'shoe_size' => 37,
                'clothing_size' => 'XS',
                'bio' => 'Фитнес-модель и амбассадор здорового образа жизни. Участвую в спортивных и wellness-проектах.',
                'languages' => ['Русский'],
                'skills' => ['Фитнес', 'Спортивное позирование', 'Lifestyle'],
                'instagram' => 'alina_kozlova_fit',
                'categories' => ['fitness', 'lifestyle', 'commercial'],
                'status' => 'active',
                'is_featured' => true,
                'experience_years' => 2,
            ],
            [
                'first_name' => 'Полина',
                'last_name' => 'Морозова',
                'email' => 'polina.morozova@example.com',
                'phone' => '+7 (999) 111-11-07',
                'birth_date' => '1999-12-25',
                'gender' => 'female',
                'city' => 'Санкт-Петербург',
                'height' => 179,
                'weight' => 57,
                'bust' => 88,
                'waist' => 62,
                'hips' => 92,
                'eye_color' => 'Зеленые',
                'hair_color' => 'Рыжая',
                'shoe_size' => 39,
                'clothing_size' => 'S',
                'bio' => 'Яркая индивидуальность с уникальной внешностью. Люблю креативные и концептуальные съемки.',
                'languages' => ['Русский', 'Английский', 'Немецкий'],
                'skills' => ['Концептуальные съемки', 'Art', 'Эдиториал'],
                'instagram' => 'polina_morozova_art',
                'categories' => ['editorial', 'art', 'fashion'],
                'status' => 'active',
                'is_featured' => true,
                'experience_years' => 5,
            ],
            [
                'first_name' => 'София',
                'last_name' => 'Волкова',
                'email' => 'sofia.volkova@example.com',
                'phone' => '+7 (999) 111-11-08',
                'birth_date' => '2002-04-08',
                'gender' => 'female',
                'city' => 'Новосибирск',
                'height' => 173,
                'weight' => 51,
                'bust' => 82,
                'waist' => 56,
                'hips' => 86,
                'eye_color' => 'Карие',
                'hair_color' => 'Брюнетка',
                'shoe_size' => 37,
                'clothing_size' => 'XS',
                'bio' => 'Модель plus-size с позитивным настроем. Продвигаю идеи бодипозитива и принятия себя.',
                'languages' => ['Русский'],
                'skills' => ['Plus-size', 'Коммерческая съемка', 'Lifestyle'],
                'instagram' => 'sofia_volkova',
                'categories' => ['plus-size', 'commercial', 'lifestyle'],
                'status' => 'active',
                'is_featured' => false,
                'experience_years' => 2,
            ],
            [
                'first_name' => 'Кристина',
                'last_name' => 'Павлова',
                'email' => 'kristina.pavlova@example.com',
                'phone' => '+7 (999) 111-11-09',
                'birth_date' => '2000-08-14',
                'gender' => 'female',
                'city' => 'Москва',
                'height' => 181,
                'weight' => 59,
                'bust' => 90,
                'waist' => 63,
                'hips' => 93,
                'eye_color' => 'Голубые',
                'hair_color' => 'Блондинка',
                'shoe_size' => 40,
                'clothing_size' => 'M',
                'bio' => 'Высокая модель с опытом работы на подиумах. Участвовала в показах российских дизайнеров.',
                'languages' => ['Русский', 'Английский'],
                'skills' => ['Подиумная ходьба', 'Runway', 'Фотопозирование'],
                'instagram' => 'kristina_pavlova_model',
                'categories' => ['runway', 'fashion', 'commercial'],
                'status' => 'active',
                'is_featured' => true,
                'experience_years' => 4,
            ],
            [
                'first_name' => 'Ольга',
                'last_name' => 'Семенова',
                'email' => 'olga.semenova@example.com',
                'phone' => '+7 (999) 111-11-10',
                'birth_date' => '2001-02-20',
                'gender' => 'female',
                'city' => 'Краснодар',
                'height' => 175,
                'weight' => 54,
                'bust' => 85,
                'waist' => 59,
                'hips' => 89,
                'eye_color' => 'Серые',
                'hair_color' => 'Шатенка',
                'shoe_size' => 38,
                'clothing_size' => 'S',
                'bio' => 'Универсальная модель, работаю в разных жанрах. Легко адаптируюсь к любым задачам.',
                'languages' => ['Русский', 'Английский'],
                'skills' => ['Универсальность', 'Фото', 'Видео'],
                'instagram' => 'olga_semenova',
                'categories' => ['commercial', 'catalog', 'lifestyle'],
                'status' => 'active',
                'is_featured' => false,
                'experience_years' => 2,
            ],
            // Мужские модели
            [
                'first_name' => 'Александр',
                'last_name' => 'Лебедев',
                'email' => 'alexander.lebedev@example.com',
                'phone' => '+7 (999) 111-11-11',
                'birth_date' => '1997-06-10',
                'gender' => 'male',
                'city' => 'Москва',
                'height' => 188,
                'weight' => 82,
                'bust' => 100,
                'waist' => 80,
                'shoe_size' => 43,
                'clothing_size' => 'L',
                'eye_color' => 'Карие',
                'hair_color' => 'Шатен',
                'bio' => 'Профессиональная мужская модель. Работал с ведущими мужскими журналами GQ, Esquire.',
                'languages' => ['Русский', 'Английский'],
                'skills' => ['Подиумная ходьба', 'Фотопозирование', 'Актерское мастерство'],
                'instagram' => 'alex_lebedev_model',
                'categories' => ['fashion', 'runway', 'commercial'],
                'status' => 'active',
                'is_featured' => true,
                'experience_years' => 6,
            ],
            [
                'first_name' => 'Дмитрий',
                'last_name' => 'Королев',
                'email' => 'dmitry.korolev@example.com',
                'phone' => '+7 (999) 111-11-12',
                'gender' => 'male',
                'birth_date' => '1999-03-25',
                'city' => 'Санкт-Петербург',
                'height' => 185,
                'weight' => 78,
                'bust' => 98,
                'waist' => 78,
                'shoe_size' => 42,
                'clothing_size' => 'L',
                'eye_color' => 'Голубые',
                'hair_color' => 'Блондин',
                'bio' => 'Молодая перспективная модель. Специализируюсь на спортивной и lifestyle съемке.',
                'languages' => ['Русский', 'Английский'],
                'skills' => ['Спорт', 'Lifestyle', 'Фитнес'],
                'instagram' => 'dmitry_korolev',
                'categories' => ['fitness', 'lifestyle', 'commercial'],
                'status' => 'active',
                'is_featured' => true,
                'experience_years' => 3,
            ],
            [
                'first_name' => 'Максим',
                'last_name' => 'Орлов',
                'email' => 'maxim.orlov@example.com',
                'phone' => '+7 (999) 111-11-13',
                'birth_date' => '1995-11-08',
                'gender' => 'male',
                'city' => 'Москва',
                'height' => 190,
                'weight' => 85,
                'bust' => 102,
                'waist' => 82,
                'shoe_size' => 44,
                'clothing_size' => 'L',
                'eye_color' => 'Зеленые',
                'hair_color' => 'Брюнет',
                'bio' => 'Опытная модель с атлетическим телосложением. Работаю в fashion и спортивных проектах.',
                'languages' => ['Русский', 'Английский', 'Испанский'],
                'skills' => ['Подиум', 'Фитнес', 'Актерское мастерство'],
                'instagram' => 'maxim_orlov_official',
                'categories' => ['fashion', 'fitness', 'commercial'],
                'status' => 'active',
                'is_featured' => true,
                'experience_years' => 8,
            ],
            [
                'first_name' => 'Артем',
                'last_name' => 'Медведев',
                'email' => 'artem.medvedev@example.com',
                'phone' => '+7 (999) 111-11-14',
                'birth_date' => '2000-07-19',
                'gender' => 'male',
                'city' => 'Казань',
                'height' => 183,
                'weight' => 75,
                'bust' => 96,
                'waist' => 76,
                'shoe_size' => 42,
                'clothing_size' => 'M',
                'eye_color' => 'Карие',
                'hair_color' => 'Шатен',
                'bio' => 'Начинающая модель с перспективой роста. Открыт к новым проектам и сотрудничеству.',
                'languages' => ['Русский'],
                'skills' => ['Фотопозирование', 'Коммерческая съемка'],
                'instagram' => 'artem_medvedev',
                'categories' => ['commercial', 'catalog', 'lifestyle'],
                'status' => 'active',
                'is_featured' => false,
                'experience_years' => 1,
            ],
            [
                'first_name' => 'Никита',
                'last_name' => 'Соловьев',
                'email' => 'nikita.solovev@example.com',
                'phone' => '+7 (999) 111-11-15',
                'birth_date' => '1998-04-05',
                'gender' => 'male',
                'city' => 'Москва',
                'height' => 187,
                'weight' => 80,
                'bust' => 99,
                'waist' => 79,
                'shoe_size' => 43,
                'clothing_size' => 'L',
                'eye_color' => 'Серые',
                'hair_color' => 'Русый',
                'bio' => 'Модель с опытом работы в рекламе премиум-брендов. Участвовал в кампаниях часовых и автомобильных брендов.',
                'languages' => ['Русский', 'Английский'],
                'skills' => ['Luxury', 'Премиум реклама', 'Портрет'],
                'instagram' => 'nikita_solovev',
                'categories' => ['commercial', 'luxury', 'editorial'],
                'status' => 'active',
                'is_featured' => true,
                'experience_years' => 5,
            ],
            [
                'first_name' => 'Игорь',
                'last_name' => 'Федоров',
                'email' => 'igor.fedorov@example.com',
                'phone' => '+7 (999) 111-11-16',
                'birth_date' => '2001-09-12',
                'gender' => 'male',
                'city' => 'Екатеринбург',
                'height' => 184,
                'weight' => 77,
                'bust' => 97,
                'waist' => 77,
                'shoe_size' => 42,
                'clothing_size' => 'L',
                'eye_color' => 'Голубые',
                'hair_color' => 'Блондин',
                'bio' => 'Молодая модель, активно развиваюсь в индустрии. Работаю над собственным стилем.',
                'languages' => ['Русский', 'Английский'],
                'skills' => ['Фото', 'Видео', 'Реклама'],
                'instagram' => 'igor_fedorov_model',
                'categories' => ['commercial', 'lifestyle', 'catalog'],
                'status' => 'active',
                'is_featured' => false,
                'experience_years' => 2,
            ],
            [
                'first_name' => 'Роман',
                'last_name' => 'Захаров',
                'email' => 'roman.zakharov@example.com',
                'phone' => '+7 (999) 111-11-17',
                'birth_date' => '1996-12-30',
                'gender' => 'male',
                'city' => 'Санкт-Петербург',
                'height' => 189,
                'weight' => 83,
                'bust' => 101,
                'waist' => 81,
                'shoe_size' => 44,
                'clothing_size' => 'L',
                'eye_color' => 'Карие',
                'hair_color' => 'Брюнет',
                'bio' => 'Опытная модель подиума. Участвовал в показах Russian Fashion Week и других крупных событиях.',
                'languages' => ['Русский', 'Английский', 'Французский'],
                'skills' => ['Runway', 'High Fashion', 'Подиумная ходьба'],
                'instagram' => 'roman_zakharov',
                'telegram' => 'roman_zakh',
                'categories' => ['runway', 'fashion', 'editorial'],
                'status' => 'active',
                'is_featured' => true,
                'experience_years' => 7,
            ],
            [
                'first_name' => 'Сергей',
                'last_name' => 'Белов',
                'email' => 'sergey.belov@example.com',
                'phone' => '+7 (999) 111-11-18',
                'birth_date' => '1999-05-17',
                'gender' => 'male',
                'city' => 'Нижний Новгород',
                'height' => 186,
                'weight' => 79,
                'bust' => 98,
                'waist' => 78,
                'shoe_size' => 43,
                'clothing_size' => 'L',
                'eye_color' => 'Зеленые',
                'hair_color' => 'Шатен',
                'bio' => 'Универсальная модель, работаю в различных направлениях от fashion до commercial.',
                'languages' => ['Русский'],
                'skills' => ['Универсальность', 'Адаптивность', 'Профессионализм'],
                'instagram' => 'sergey_belov',
                'categories' => ['commercial', 'fashion', 'catalog'],
                'status' => 'active',
                'is_featured' => false,
                'experience_years' => 3,
            ],
            [
                'first_name' => 'Владислав',
                'last_name' => 'Кузнецов',
                'email' => 'vladislav.kuznetsov@example.com',
                'phone' => '+7 (999) 111-11-19',
                'birth_date' => '2002-01-22',
                'gender' => 'male',
                'city' => 'Ростов-на-Дону',
                'height' => 182,
                'weight' => 74,
                'bust' => 95,
                'waist' => 75,
                'shoe_size' => 41,
                'clothing_size' => 'M',
                'eye_color' => 'Серые',
                'hair_color' => 'Русый',
                'bio' => 'Новая звезда модельного мира. Талантливый и амбициозный.',
                'languages' => ['Русский', 'Английский'],
                'skills' => ['Фотопозирование', 'Видео', 'Актерское мастерство'],
                'instagram' => 'vlad_kuznetsov',
                'categories' => ['commercial', 'lifestyle', 'fashion'],
                'status' => 'active',
                'is_featured' => false,
                'experience_years' => 1,
            ],
            [
                'first_name' => 'Андрей',
                'last_name' => 'Васильев',
                'email' => 'andrey.vasilev@example.com',
                'phone' => '+7 (999) 111-11-20',
                'birth_date' => '1997-10-03',
                'gender' => 'male',
                'city' => 'Москва',
                'height' => 191,
                'weight' => 86,
                'bust' => 103,
                'waist' => 83,
                'shoe_size' => 45,
                'clothing_size' => 'XL',
                'eye_color' => 'Карие',
                'hair_color' => 'Брюнет',
                'bio' => 'Высокая модель с впечатляющими параметрами. Специализируюсь на high fashion и подиумных показах.',
                'languages' => ['Русский', 'Английский', 'Итальянский'],
                'skills' => ['Runway', 'High Fashion', 'Эдиториал'],
                'instagram' => 'andrey_vasilev_model',
                'telegram' => 'andrey_vas',
                'categories' => ['runway', 'fashion', 'editorial'],
                'status' => 'active',
                'is_featured' => true,
                'experience_years' => 6,
            ],
        ];

        // Очищаем таблицу моделей перед добавлением
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        ModelProfile::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        
        foreach ($models as $index => $modelData) {
            // Вычисляем возраст
            $birthDate = new \DateTime($modelData['birth_date']);
            $now = new \DateTime();
            $age = $now->diff($birthDate)->y;
            $modelData['age'] = $age;

            ModelProfile::create($modelData);
        }

        $this->command->info('20 моделей успешно добавлено!');
    }
}
